import { ApiProperty } from '@nestjs/swagger';
import { Expose, Type } from 'class-transformer';
import { IsInt, IsNotEmpty, IsString, MaxLength } from 'class-validator';
import { InvoiceCustomerDto } from './invoice-customer';
import { InvoiceDetailDto } from './invoice-detail.dto';

export class InvoiceDto {
  /**
   * The internal autogenerated id
   * @example 1
   */
  @Expose()
  @ApiProperty({
    description: 'The internal autogenerated id of the Invoice'
  })
  invoiceId: number;

  @IsString()
  @IsNotEmpty()
  @Expose()
  @MaxLength(12)
  @ApiProperty({
    example: 'LC',
    description: 'The Invoice'
  })
  invoice: string;

  @IsInt()
  @Expose()
  @ApiProperty({
    example: '1',
    description: 'The customer Id'
  })
  customerId: number;

  @Expose()
  @ApiProperty({
    description: 'Customer of the Invoice',
    type: InvoiceCustomerDto
  })
  @Type(() => InvoiceCustomerDto)
  customer: InvoiceCustomerDto;

  @Expose()
  @ApiProperty({
    description: 'Details of the Invoice',
    type: InvoiceDetailDto
  })
  @Type(() => InvoiceDetailDto)
  @Expose()
  invoiceDetails: InvoiceDetailDto[];

  @Expose()
  @ApiProperty({
    description: 'The date of the Invoice'
  })
  date: Date;

  @Expose()
  @ApiProperty({
    example: '10',
    description: 'The subtotal of the invoice'
  })
  subtotal: number;

  @Expose()
  @ApiProperty({
    example: '10',
    description: 'The total of the invoice'
  })
  total: number;

  @Expose()
  @ApiProperty({
    example: '10',
    description: 'The taxes of the invoice'
  })
  taxes: number;

  @Expose()
  @ApiProperty({
    example: '10',
    description: 'The percentage of taxes of the invoice'
  })
  taxesPercentage: number;

  @Expose()
  @ApiProperty({
    description: 'The creation date of the Invoice'
  })
  createdAt: Date;

  @Expose()
  @ApiProperty({
    description: 'The user who created the Invoice'
  })
  createdBy: string;

  @Expose()
  @ApiProperty({
    description: 'The last update date of the Invoice'
  })
  updatedAt: Date;

  @Expose()
  @ApiProperty({
    description: 'The user who updated the Invoice'
  })
  updatedBy: string;
}
