import { ApiProperty } from '@nestjs/swagger';
import { Expose } from 'class-transformer';
import { IsNotEmpty, IsString, MaxLength } from 'class-validator';

export class TitleDto {
  /**
   * The internal autogenerated id
   * @example 1
   */
  @Expose()
  @ApiProperty({
    description: 'The internal autogenerated id of the title'
  })
  titleId: number;

  @IsString()
  @IsNotEmpty()
  @Expose()
  @MaxLength(24)
  @ApiProperty({
    example: 'Sr',
    description: 'The title'
  })
  name: string;

  @Expose()
  @ApiProperty({
    description: 'The creation date of the title'
  })
  createdAt: Date;

  @Expose()
  @ApiProperty({
    description: 'The user who created the title'
  })
  createdBy: string;

  @Expose()
  @ApiProperty({
    description: 'The last update date of the title'
  })
  updatedAt: Date;

  @Expose()
  @ApiProperty({
    description: 'The user who updated the title'
  })
  updatedBy: string;
}
