import { ApiHideProperty, ApiProperty } from '@nestjs/swagger';
import { Exclude, Expose } from 'class-transformer';
import { IsNotEmpty, IsString, MaxLength } from 'class-validator';

export class PhoneDto {
  /**
   * The internal autogenerated id
   * @example 1
   */
  @Expose()
  @ApiProperty({
    description: 'The internal autogenerated id of the phone'
  })
  phoneId: number;

  @Exclude()
  @ApiHideProperty()
  @ApiProperty({
    description: 'The internal autogenerated id of the customer'
  })
  customerId: number;

  @IsString()
  @IsNotEmpty()
  @Expose()
  @MaxLength(16)
  @ApiProperty({
    example: '31 06 43006576',
    description: 'The phone number'
  })
  number: string;
}
