import { ApiProperty } from '@nestjs/swagger';
import { Expose } from 'class-transformer';
import { IsNotEmpty, IsString, MaxLength } from 'class-validator';

export class DocumentTypeDto {
  /**
   * The internal autogenerated id
   * @example 1
   */
  @Expose()
  @ApiProperty({
    description: 'The internal autogenerated id of the document type'
  })
  documentTypeId: number;

  @IsString()
  @IsNotEmpty()
  @Expose()
  @MaxLength(36)
  @ApiProperty({
    example: 'Passport',
    description: 'The document type'
  })
  name: string;

  @Expose()
  @ApiProperty({
    description: 'The creation date of the document type'
  })
  createdAt: Date;

  @Expose()
  @ApiProperty({
    description: 'The user who created the document type'
  })
  createdBy: string;

  @Expose()
  @ApiProperty({
    description: 'The last update date of the document type'
  })
  updatedAt: Date;

  @Expose()
  @ApiProperty({
    description: 'The user who updated the document type'
  })
  updatedBy: string;
}
