import { ApiHideProperty, ApiProperty } from '@nestjs/swagger';
import { Exclude, Expose } from 'class-transformer';
import { IsNotEmpty, IsString, MaxLength } from 'class-validator';

export class EmailDto {
  /**
   * The internal autogenerated id
   * @example 1
   */
  @Expose()
  @ApiProperty({
    description: 'The internal autogenerated id of the email'
  })
  emailId: number;

  @Exclude()
  @ApiHideProperty()
  @ApiProperty({
    description: 'The internal autogenerated id of the customer'
  })
  customerId: number;

  @IsString()
  @IsNotEmpty()
  @Expose()
  @MaxLength(120)
  @ApiProperty({
    example: 'John@hotmail.com',
    description: 'The email'
  })
  email: string;
}
